### ISSUE TITLE
Calibration files for 1280x720

### ISSUE THREAD

**Issue by christjt** [qian256/HoloLensCamCalib#5]
Hey,

Some really great info here! You would not happen to have the camera calibration files for 720p resolution of the HoloLens Webcam aswell?

Thanks,
Chris

**Comment by qian256** [comment]
I added the 720p calibration files. I am curious why you would like to have 720p resolution. In my opinion, 896x504 is good for fast processing, and 1344x756 has wide FOV, but 1280x720 does not seem to have significant benefits.

**Comment by christjt** [comment]
Hello, sorry for the extremely late reply. First of I am more interested in the most exact positioning / results rather than performance, it does not have to be fast processing. And by that reasoning using 1344x756 doesn't make sense as the pixel density per FOV is pretty much the same given the wide angle. 

After researching this for some time I came to the conclusion that calibrating these intrinsics may not yield anything. First of all when ripping images (both video and photo) from the HoloLens, the image processing pipeline actually undistorts the images (https://docs.microsoft.com/en-us/windows/mixed-reality/locatable-camera, see under distortion error) so we should assume no distortion and disregard the distortion coefficients. To fetch the focal length and principal point we can simply find this information in the projection matrix(https://docs.microsoft.com/en-us/windows/mixed-reality/locatable-camera, see images with coordinate systems) or even use the UWP API (https://docs.microsoft.com/en-us/uwp/api/windows.media.devices.core.cameraintrinsics). And in retrospect, it makes sense that these are known as the HoloLens has built in recording capabilities and these values are needed to correctly project holograms onto the images from the camera while recording.

I'd love to hear your input on this though. I may have misunderstood.

**Comment by qian256** [comment]
Yes HoloLens undistort the images that we get, and there is a projection matrix for the image.
What I am doing is to use the undistorted image, ignore the projection matrix provided by UWP, and treat those images as from a "normal" camera.
I did this simply because the projection matrix of the image does not align the virtual content and the background well. I am not sure if you have experience with HoloLens recording with Hologram. If you put some hologram at a certain location, the recording does have offset/error, which means that the projection matrix is not exactly correct. Also, the camera calibration results from OpenCV also shows there still exists some distortion.
But I agree, if the projection matrix and undistortion function provided by UWP API are good enough. This camera calibration will not be needed any more. It is quite possible in the future

**Comment by christjt** [comment]
I see, so the "built in" projection simply is off when factory calibrated then. I agree that the recording does contain a substantial error. I wonder why they don't calibrate it better? They definitely do some sort of calibration when making the HoloLenses as each device has different intrinsics given by the API.   Again great work! ~~How did you go about to get the distorted images from the HoloLens?~~

EDIT: Was able to fetch the preview stream, feel free to close issue
